language: ruby
os: linux
dist: xenial
cache:
  bundler: true

addons:
  chrome: stable

before_install:
  - CHROME_VERSION=`/opt/google/chrome/chrome --version | grep -Po '(?<=Google Chrome )[^.]+'`
  - LATEST_CHROMEDRIVER=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
  - wget http://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - mv chromedriver /home/travis/bin/
