name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  matrix:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ '3.2', '3.1', '3.0', '2.7', 'jruby' ]
        gemfile:
          - 'rails70_gems.rb'
          - 'rails61_gems.rb'
        exclude:
          - ruby-version: jruby
            gemfile: rails70_gems.rb
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
